## Amate Shivdas Maruti

## ID:AIS022

### Arrays and String:

### 1. What is an array?

Ans: An array is an object that stores a group of elements or (values) of same datatypes. Arrays can store only one type of data. for example-integer type value or string or character type values.

### 2. What is difference between array and list

Ans:List is similar to an array that consists f group of elements. A list can stores a group of elements of different datatypes. List do not have a fixed size.
 
 An array is an object that stores a group of elements or (values) of same datatypes. Array have a fixed sized.

### 3. How to change the shape of an array?
Ans- We can used reshape() function to change the shape of an array. for example- arr = arange(10)

In [2]:
import numpy as np
arr=np.arange(10)
print(arr)
v=arr.reshape(2,5)
print(v)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 4. What does the name.strip()do?
Ans: The strip() function is used to remove the space of a string from both left as well as rith side.

In [3]:
str1=" python "
str1.strip()

'python'

### 5. When we use triple single or triple double quotes to define a string?

Ans: When we want to dislay the paragraph or to print multiple lines then we use single('''  ''') or ("""  """) triple quotes.

### 6. Create a character type array using numpy?

In [7]:
import numpy as np
aar1=np.array(['a','b','c','d'])
print(aar1)
type(aar1)

['a' 'b' 'c' 'd']


numpy.ndarray

### 7. Create a hello string and access the string character "ll" in python?

In [9]:
str_1="hello"
print(str_1)
print(str_1[2:4])

hello
ll


### 8) Create an array to get largest and smallest number using minimum and maximum function?

In [13]:
from numpy import *
arr1=np.array([22,40,79,90,12,])
print(arr1)
a=min(arr1)
print(a)
b=max(arr1)
print(b)

[22 40 79 90 12]
12
90


### 9. If name is “core python” then access the "python" from name and reverse "python" using slicing?

In [14]:
name="core python"
a=name[5:11]
print(a)
b=name[-1:-7:-1]
print(b)

python
nohtyp


### 10. Create an array of integer type and add element 12 using append method and remove one element using remove methods?

In [15]:
from array import *
arr1=array("i",[1,5,7,8,4])
arr1.append(12)
arr1.remove(7)
arr1.remove(1)
print(arr1)

array('i', [5, 8, 4, 12])


### 11. Create a single dimensional and 3 dimensional array using numpy?

In [16]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[4,5,6],[2,8,9],[1,2,6]])
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[4 5 6]
 [2 8 9]
 [1 2 6]]


### 12. Create a "Programiz" string and convert the string into upper, lower case? and replace given string by "program" using replace method?

In [18]:
str="Programiz"
a=str.upper()
b=str.lower()
c=str.replace("Programiz","program")
print(a,b,c)

PROGRAMIZ programiz program


### 13. Create an two array one using linspace and another using arange function and then subract array1 from array2?

In [21]:
from numpy import *
arr1=np.linspace(2,10,5)
print(arr1)
arr2=np.arange(12,17,1)
print(arr2)
sub=arr2-arr1
print(sub)

[ 2.  4.  6.  8. 10.]
[12 13 14 15 16]
[10.  9.  8.  7.  6.]


### 14. Create a "happy new year" string and then separate this string by(space) " " ?

In [23]:
str1="happy new year"
d=str1.split(" ")
print(d)
str2="happy:new:year"
d=str2.split(":")
print(d)

['happy', 'new', 'year']
['happy', 'new', 'year']
